version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: blog-user
      MYSQL_PASSWORD: supersecret
      MYSQL_ROOT_PASSWORD: supersecret

  ghost-api:
    build: ./backend
    image: ghost:3.18
    container_name: ghost-api
    volumes:
      - ghost-api:/var/lib/ghost-api
    restart: always
    ports:
      - 8000:2368
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: blog-user
      database__connection__password: supersecret
      database__connection__database: mysql
    depends_on:
      - mysql
    entrypoint: ["wait-for-db.sh", "mysql", "--", "docker-entrypoint.sh"]
    command: ["node", "current/index.js"]
  
  frontend:
    build: ./frontend
    image: node:12
    container_name: frontend
    volumes:
      - frontend:/var/lib/frontend
    restart: always
    ports:
      - 3000:3000
    command:  [ "yarn", "start" ]
volumes:
  mysql: {}
  ghost-api: {}
  frontend: {}
